### ISSUE TITLE
Problem with numers and special characters

### ISSUE THREAD

**Issue by jaro1122334455** [Blake-Madden/Quneiform#8]
Hello,

I think I found another problem whith code shown below:
```
bool MainWindow::importProject()
{
    if (true)
    {
    	QApplication::setApplicationName("TEST  1");
    	QApplication::setApplicationName("TEST  2 test");
    	QApplication::setApplicationName("TEST  +");	
    	QApplication::setApplicationName("TEST  \n");
    	QApplication::setApplicationName("TEST zmiana 1");
        return false;
    }
}
```
Result:
```
File	Line	Column	Value	Explanation	WarningID
"test.cpp"	6	40	"TEST  2 test"	"String not available for translation in function call: QApplication::setApplicationName"	[notL10NAvailable]
"test.cpp"	11	40	"TEST zmiana 1"	"String not available for translation in function call: QApplication::setApplicationName"	[notL10NAvailable]
```
It doesn't report errors when special ascii character or number is entered as the second word.

**Comment by Blake-Madden** [comment]
I'll check it out.

On an unrelated note, I probably shouldn't be saying that anything inside of `QApplication::setApplicationName` should be made available for translation. IMO you wouldn't normally want an app's name to be localized.

**Comment by Blake-Madden** [comment]
If you pass `--min-l10n-wordcount=1` to the command line it should pick up all five strings. I'm not treating `+` or `1` as a word, so `TEST 1` and `TEST +` are considered one-word strings.

I will be pushing an update to not complain about strings inside of `QApplication::setApplicationName`, so for this particular example it will report 0 issues in the near future.
